# Generated by Django 3.2.5 on 2021-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(help_text="voter's firstname", max_length=50)),
                ('lastname', models.CharField(help_text="voter's lastname (Surname)", max_length=50)),
                ('address', models.CharField(blank=True, help_text="voter's address (Optional).", max_length=150, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('AGENT', 'AGENT'), ('VOTER', 'VOTER')], default='VOTER', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('polliing_unit_unique_id', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=180)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Agents (Voters)',
                'verbose_name_plural': 'Agents (Voters)',
                'unique_together': {('firstname', 'lastname')},
            },
        ),
    ]
