# Generated by Django 3.2.5 on 2021-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(choices=[('Aniocha North', 'Aniocha North'), ('Aniocha - South', 'Aniocha - South'), ('Ethiope East', 'Ethiope East'), ('Ethiope West', 'Ethiope West'), ('Ika North - East', 'Ika North - East'), ('Ika - South', 'Ika- South'), ('Isoko North', 'Isoko North'), ('Isoko South', 'Isoko South'), ('Ndokwa East', 'Ndokwa East'), ('Ndokwa West', 'Ndokwa West'), ('Okpe', 'Okpe'), ('Oshimili - North', 'Oshimili - North'), ('Oshimili - South', 'Oshimili - South'), ('Patani', 'Patani'), ('Sapele', 'Sapele'), ('Udu', 'Udu'), ('Ughelli North', 'Ughelli North'), ('Ughelli South', 'Ughelli South'), ('Ukwuani', 'Ukwuani'), ('Uvwie', 'Uvwie'), ('Bomadi', 'Bomadi'), ('Burutu', 'Burutu'), ('Warri North', 'Warri North'), ('Warri South', 'Warri South'), ('Warri South West', 'Warri South West')], max_length=30)),
                ('lga_id', models.PositiveIntegerField()),
                ('lga_description', models.CharField(max_length=200)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(choices=[('PDP', 'PDP'), ('DPP', 'DPP'), ('ACN', 'ACN'), ('PPA', 'PPA'), ('CDC', 'CDC'), ('JP', 'JP'), ('ANPP', 'ANPP'), ('LABOUR', 'LABOUR'), ('CPP', 'CPP')], max_length=7)),
                ('party_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PollngUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_id', models.PositiveIntegerField()),
                ('polling_unit_number', models.PositiveIntegerField()),
                ('polling_unit_name', models.CharField(max_length=70)),
                ('polling_unit_description', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=70)),
                ('long', models.CharField(max_length=70)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=5)),
                ('state_name', models.CharField(choices=[(1, 'Abuja'), (2, 'Abia'), (3, 'Anambra'), (4, 'Akwa Ibom'), (5, 'Adamawa'), (6, 'Bauchi'), (7, 'Bayelsa'), (8, 'Benue'), (9, 'Borno'), (10, 'Cross River'), (12, 'Ebonyi'), (13, 'Edo'), (14, 'Ekiti'), (15, 'Enugu'), (16, 'Gombe'), (17, 'Imo'), (18, 'Jigawa'), (19, 'Kaduna'), (20, 'Kano'), (21, 'Katsina'), (22, 'Kebbi'), (23, 'Kogi'), (24, 'Kwara'), (25, 'Delta'), (26, 'Nasarawa'), (27, 'Niger'), (28, 'Ogun'), (29, 'Ondo'), (30, 'Osun'), (31, 'Oyo'), (32, 'Plateau'), (33, 'Rivers'), (34, 'Sokoto'), (35, 'Taraba'), (36, 'Yobe'), (37, 'Zamfara'), (251, 'Lagos')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.PositiveIntegerField()),
                ('ward_name', models.CharField(max_length=70)),
                ('ward_description', models.CharField(max_length=200)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
