# Generated by Django 3.2.5 on 2021-08-05 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('state_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='entered_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='lga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_data.states'),
        ),
        migrations.AddField(
            model_name='pollngunit',
            name='entered_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollngunit',
            name='lga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_data.lga'),
        ),
        migrations.AddField(
            model_name='pollngunit',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_data.ward'),
        ),
        migrations.AddField(
            model_name='lga',
            name='entered_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='state_data.states', verbose_name='State-Id'),
        ),
    ]
