# Generated by Django 3.2.6 on 2021-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lga',
            options={'verbose_name': 'LGA', 'verbose_name_plural': "LGA's"},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterField(
            model_name='states',
            name='state_name',
            field=models.CharField(choices=[('1', 'Abuja'), ('2', 'Abia'), ('3', 'Anambra'), ('4', 'Akwa Ibom'), ('5', 'Adamawa'), ('6', 'Bauchi'), ('7', 'Bayelsa'), ('8', 'Benue'), ('9', 'Borno'), ('10', 'Cross River'), ('12', 'Ebonyi'), ('13', 'Edo'), ('14', 'Ekiti'), ('15', 'Enugu'), ('16', 'Gombe'), ('17', 'Imo'), ('18', 'Jigawa'), ('19', 'Kaduna'), ('20', 'Kano'), ('21', 'Katsina'), ('22', 'Kebbi'), ('23', 'Kogi'), ('24', 'Kwara'), ('25', 'Delta'), ('26', 'Nasarawa'), ('27', 'Niger'), ('28', 'Ogun'), ('29', 'Ondo'), ('30', 'Osun'), ('31', 'Oyo'), ('32', 'Plateau'), ('33', 'Rivers'), ('34', 'Sokoto'), ('35', 'Taraba'), ('36', 'Yobe'), ('37', 'Zamfara'), ('251', 'Lagos')], max_length=30),
        ),
    ]
