# Generated by Django 3.2.6 on 2021-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0003_auto_20210805_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(choices=[('PDP', 'PDP'), ('DPP', 'DPP'), ('ACN', 'ACN'), ('PPA', 'PPA'), ('CDC', 'CDC'), ('JP', 'JP'), ('ANPP', 'ANPP'), ('LABOUR', 'LABOUR'), ('CPP', 'CPP')], max_length=10),
        ),
    ]
