# Generated by Django 3.2.6 on 2021-08-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0004_auto_20210805_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollngunit',
            name='lga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_data.lga', verbose_name='LGA-Id'),
        ),
        migrations.AlterField(
            model_name='pollngunit',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_data.ward', verbose_name='Ward-Id'),
        ),
    ]
