# Generated by Django 3.2.6 on 2021-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0005_auto_20210805_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='lga_id',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_id',
            field=models.CharField(max_length=70),
        ),
    ]
