# Generated by Django 3.2.6 on 2021-08-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0006_auto_20210805_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollngunit',
            old_name='lat',
            new_name='lattitude',
        ),
        migrations.RenameField(
            model_name='pollngunit',
            old_name='long',
            new_name='longitude',
        ),
    ]
